### PR TITLE
add .sublime-color-scheme format

### PR DESCRIPTION
**Pull request by aidenfoxivey**
This is just the artifact of conversion - I haven't examined it too closely to figure out how reasonable it is or not.

### CODE REVIEW

**Comment by aidenfoxivey** [comment]
That said, it's generated via PackageDev, so I trust it 85%.

**Comment by aidenfoxivey** [comment]
Would close #1

**Comment by dkter** [comment]
sorry, didn't get around to testing this until now, but it seems to work on my machine!

**Comment by dkter** [comment]
thanks 🙏

**Pull request merged**
